# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Print the user name ${{ secrets.DOCKERHUB_USERNAME }} ."
      
      - name: Login to DockerHub windows
        uses: docker/login-action@v1
        
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: urjaya/jdimage:latest
          
  integration-testing:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:    
      - name: docker-Image-run    
        run: |
          docker run urjaya/jdimage
          
      - name: integration-testing
        run: echo "testing successfull"
  
      - name: Docker container stop
        run: |
          docker stop $(docker ps -q)
