# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build-push:
    name: checkout build image and push docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Print the user name ${{ secrets.DOCKERHUB_USERNAME }} ."
      
      - name: Login to DockerHub windows
        uses: docker/login-action@v1
        
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: urjaya/jdimage:latest
          
  integration-testing:
    name: docker-run integeration test and destroy the instance
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: stop and remove all docker containers
        run: |
          sudo chmod 666 /var/run/docker.sock
          ids=$(docker ps -a -q)
          for id in $ids
          do
          echo "$id"
          docker stop $id && docker rm $id
          done
        
      - name: docker-compose-image-build-run    
        run: docker-compose up -d
          
      - name: call health check api
        uses: satak/webrequest-action@master
        with:   
          url: https://localhost:5000/
          method: GET
          run: |
            echo "health check successfull"
          
      - name: integration-testing
        run: echo "test successfull"
  
      - name: Destroy docker container
        run: |
          sudo chmod 666 /var/run/docker.sock
          ids=$(docker ps -a -q)
          for id in $ids
          do
          echo "$id"
          docker stop $id && docker rm $id
          done
